### ISSUE TITLE
Incorrect typechain repo in github dependency graph

### ISSUE THREAD

**Issue by zemse** [dethcrypto/TypeChain#257]
If you check the dependency graph of any repo that uses Typechain core package, it points to [nomadcoders/typechain](https://github.com/nomadcoders/typechain).

You can see the second last dependency in [here](https://github.com/KMPARDS/esn-contracts/network/dependencies).

This may be due to that repo having `typechain` in it's `package.json` file, maybe github selects the one that's older. I think having a `@typechain/core` kind of package for the core package should fix this, since I can see the first dependency `@typechain/ethers-v5` correctly mapped to this repo. I understand this is not a serious problem, but it'd be nice to see the correct dependency linked in the dependency graph.

**Comment by krzkaczor** [comment]
I think there's nothing we can do :( Github shows now that this repo is used by 320 other repos so maybe they fixed it on their end...
