### ISSUE TITLE
Enable TS errors when ethers v5 contract object does not have a method

### ISSUE THREAD

**Issue by zemse** [dethcrypto/TypeChain#276]
This [line](https://github.com/ethers-io/ethers.js/blob/d817416bae2fbc7adb8391fd038613241b7ab8ba/packages/contracts/src.ts/index.ts#L572) in the `Contract` class is pulling back the power of typescript.

```ts
const rainbowInstance = RainbowFactory.connect(address, provider);
rainbowInstance.methodThatDoesntExist(); // any
```

If solidity method `methodName` is renamed to `methodName2`, there should be typescript errors in the typescript project to be able to fix it. But ATM, it doesn't error in this case due to the wild card in the original `Contract` class.

Is there any way to disable/override this wildcard? It'd enable errors before runtime in projects! I think it can be a great addition to ethers v5 target (as well as help me to smoothly introduce breaking changes in my current project's test-net contracts in test-cases as well as UIs).

**Comment by krzkaczor** [comment]
This is definitely a problem. I tried to tackle it in the past but finally gave up. 

I see two solutions:

1. Try to use type-level-programming (`Omit`) to drop `[ key: string ]: ContractFunction | any;` It's possible to fix subtypes with wildcards using this approach (like `functions`) but I didn't have any luck fixing top-level wildcard.

2. Simply copy the whole `Contract` type and manually delete the wildcard. This approach can result in over-reliance on implementation details of ethersjs and break often in the future. 


CC: @ricmoo Maybe ethers could expose `BaseContract` type without any wildcards?
