### ISSUE TITLE
Hardhat plugin doesn't use user provided prettier cfg

### ISSUE THREAD

**Issue by krzkaczor** [dethcrypto/TypeChain#348]

**Comment by hasparus** [comment]
Hey @krzkaczor, "user provided" here means the one from user's working directory or package.json, right? (or is there a way to explicitly provide it?)

**Comment by krzkaczor** [comment]
Yes. I meant the one in user's project root. TBH: the very first thing would be to verify this issue. I am not 100% sure what happened then.

**Comment by hasparus** [comment]
I just noticed we have prettier options in `Config`, so we can pass it to `runTypeChain({ target, prettier })`. I suppose this is the thing that was broken when you wrote the issue?

```ts
export const prettierOutputTransformer: OutputTransformer = (output, { prettier }, config) => {
  const prettierCfg: PrettierOptions = { ...(config.prettier || {}), parser: 'typescript' }

  return prettier.format(output, prettierCfg)
}
```

Detecting user's Prettier config would be a nice enhancement.

Also, using user's Prettier version from `node_modules/prettier` is something we could think about, albeit I'm a little conflicted about this.

**Comment by krzkaczor** [comment]
> I just noticed we have prettier options in Config, so we can pass it to runTypeChain({ target, prettier }). I suppose this is the thing that was broken when you wrote the issue?

Yeah, perhaps.

Okay, I think I am just gonna close this issue. I see that we've been always ignoring user provided config. I'll create another (low priority) issue as I think that TC should detect if the user, uses prettier and if yes then use user-provided version and user-provided config (`.prettierrc`/package.json etc. i mean).
