### ISSUE TITLE
Obscure ways how to select certain types

### ISSUE THREAD

**Issue by Siegrift** [dethcrypto/TypeChain#376]
Hi, (and again, thanks for this library! It's awesome).

This is a more of a suggestion than a bug. The generated files currently export 2 things per contract - the factory and the contract instance type. However, it's a bit harder to do the following:
1) Parse logs of a contract without instantiating a contract instance. With ethers you can just do this:
```ts
    const contractInterface = new ethers.utils.Interface(Contract.abi);
    const parsedLog = contractInterface.parseLog(log);
```
I would like to do the same with TypeChain - however, this is not possible as of now.

2) I want to get some of the generated types. E.g. the events. For now I have to "rape" the TS with following:
```ts
type ClientRequestCreatedEvent = ReturnType<InstanceType<typeof Contract>['filters']['ClientRequestCreated']>
// or to mock the available functions
type MockedContractFunctions = { [key in keyof InstanceType<typeof Contract>['functions']]: jest.Mock };
```

**Comment by quezak** [comment]
1. Can you post a whole snippet including the "you can just do this" lines? Ethers' Contract class doesn't have a static `abi` property. Regardless, a solution was merged last week in #368, and in the next release the ABI will be available as a static property of the factory class.
2. Can you show what would you like to achieve there?

**Comment by Siegrift** [comment]
Sorry, yeah the `Contract` was not referring to the Contract class in ethers but rather the `.json` artifact of my built contract.
Imagine:

```ts
import AirnodeRrpArtifact from '../artifacts/contracts/AirnodeRrp.sol/AirnodeRrp.json';

type EthersLog = ethers.providers.Log;

declare const log: ethers.providers.Log;
const airnodeRrpInterface = new ethers.utils.Interface(AirnodeRrpArtifact.abi);
const parsedLog = airnodeRrpInterface.parseLog(log); 
console.log(parsedLog.args);
```

similarly:

```ts
type AirnodeRrpEvents = InstanceType<typeof AirnodeRrp>['filters'];
type AirnodeRrpLog<T extends keyof AirnodeRrpEvents> = ReturnType<AirnodeRrpEvents[T]>;

export function parseAirnodeRrpLog<T extends keyof AirnodeRrpEvents = never>(log: EthersLog): AirnodeRrpLog<T> {
  const airnodeRrpInterface = new ethers.utils.Interface(AirnodeRrpArtifact.abi);
  const parsedLog = airnodeRrpInterface.parseLog(log);
  return parsedLog.args as AirnodeRrpLog<T>;
}

const typedLog = parseAirnodeRrpLog<'AirnodeParametersSet'>(123 as any);
```

**Comment by quezak** [comment]
1. All right, then #368 has a fix for you, using `AirnodeRrpArtifact__factory.abi` @krzkaczor says there will be a new release in a few days :)
2. I wouldn't call it TS rape but regular usage of advanced types 😂 do you have a suggestion what could be added to make things easier?

**Comment by Siegrift** [comment]
You could export the event return types from the generated contracts? Now you generate something like:
```ts
    // a method inside a generated contract
    getAirnodeParametersAndBlockNumber(
      airnodeId: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string[], BigNumber] & {
        admin: string;
        xpub: string;
        authorizers: string[];
        blockNumber: BigNumber;
      }
    >;
```

That return value might be useful for people (at least for me is as of now). I am fine doing the advanced types thingy, but I think there should be an easier way. But the best thing I come up with is generating a named event return types which you'd export - for which you would pick a reasonable convention and it's just one more thing to maintain...

Regarding parsing the logs I think it's better if consumers implement something along my `parseAirnodeRrpLog` themselves.

**Comment by Siegrift** [comment]
Also, I'd like to import only the interface of the contract. E.g.
```ts
interface AirnodeRrpInterface extends Interface {
...
```

but this is also not exported :/

**Comment by Siegrift** [comment]
Actually, I was a bit mistaken with my example in https://github.com/ethereum-ts/TypeChain/issues/376#issue-870686826 and also https://github.com/ethereum-ts/TypeChain/issues/376#issuecomment-829155140. The problem is that the "advanced types" I created don't give me the `TypedEvent` but rather `TypedEventFilter` - the actual `TypedEvent` which I want can be `queryFilter` function on the generated contract.

Unfortunately, because `TypedEventFilter` is not exported and there is [no way to extract the generic arguments without the original interface](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgKIDcLgGLADaRTIDeAvgLABQoh8SyAKgJ4AOEAJhlmLgdADxdwAQSgBzAM6iocJgBo0mEeIkB5AEYArCAjAA+ZBAAekEOwmLuvQiQqUqNaHRTM2nJT3yEATII+jJaVkFITAAtS0dfUMTLHNLHC9oWyoqMFYUAGEAexAEKAhIVw5rZIBeRgz3KySofgBtCTAoUDEFEABXAFt1aHaOvDwAXQViOAAuZCaWkDbkdUnOnr7kBEWBvFI9VMp0tjQTGV1i6vB+BgMKhhjTeJPQ0rrQGGTQ8KD5ZGfX-xUNbV020oyGQAH4EmEVB9kAAyCHhf5RKggxYQTBQADcOz2KFQh0QYHuHl8F2QVxucQsRJqfCgvm+RDeUKgMk+DPhf0igORYI5gRZslhfIiALAPNR6Kx9ko7B0eDgBVWuSayCMasmeOaBOpZxyeQKRSqjz0GOQAHozcgAO74PDzFA49hKllRPBMKiyhDyxUIZVgVVq7wa-HHKqhXx6-KFCAnY2mi3W2325AdEAAaxA2StICAA) I was forced to modify the generated code and export this interface from `index.ts` file.

So for completeness:
```ts
// AirnodeRrp - is generated contract by TypeChain
// TypedEventFilter - is the interface created by TypeChain which I exported by modifying the generated code
import { AirnodeRrp, TypedEventFilter } from '@airnode/protocol';

// NOTE: I am also ignoring the typed tupple and only extracting the typed event object.
type ExtractTypedEvent<T> = T extends TypedEventFilter<any, infer EventArgsObject> ? EventArgsObject : never;
// I am only interested in certain events from the generated contract
export type AirnodeRrpEvents = Pick<
  InstanceType<typeof AirnodeRrp>['filters'],
  | 'ClientRequestCreated'
  | 'ClientFullRequestCreated'
  | 'ClientRequestFulfilled'
  | 'ClientRequestFailed'
  | 'WithdrawalRequested'
  | 'WithdrawalFulfilled'
>;
export type AirnodeRrpLog<T extends keyof AirnodeRrpEvents> = ExtractTypedEvent<ReturnType<AirnodeRrpEvents[T]>>;

// And I want the ethers `LogDescription`, but I want the args to be typed
export type AirnodeLogDescription<T> = Omit<ethers.utils.LogDescription, 'args'> & { args: T };


// I can then parse the logs and return typed response with
export function parseAirnodeRrpLog<T extends keyof AirnodeRrpEvents>(
  log: ethers.providers.Log
): AirnodeLogDescription<AirnodeRrpLog<T>> {
  const airnodeRrpInterface = new ethers.utils.Interface(AirnodeRrpArtifact.abi);
  const parsedLog = airnodeRrpInterface.parseLog(log);
  return parsedLog as AirnodeLogDescription<AirnodeRrpLog<T>>;
}
```

I then use it in other parts of codebase like this:
```ts
const event = fixtures.evm.logs.buildClientRequest(); // creates a mock of the request
const parsedLog = parseAirnodeRrpLog<'ClientRequestCreated'>(event);
    
// and I can strongly type the parsed logs with
type WithdrawalRequestLog = AirnodeLogDescription<AirnodeRrpLog<'WithdrawalFulfilled'>>
```

What I propose is to export the interface of generated code. This includes:
- Types defined in `commons.d.ts`
- Export generated interface for smart contracts (e.g. `AirnodeRrpInterface` in my case), such that one can type the following code:
```ts
const airnodeRrpInterface: AirnodeRrpInterface = new ethers.utils.Interface(AirnodeRrpArtifact.abi);
```
- Maybe generate a method for parsing typed events on the contract interface - similarly to how my `parseAirnodeRrpLog` works?

**Comment by Siegrift** [comment]
Hi, 

actually https://github.com/dethcrypto/TypeChain/releases/tag/%40typechain%2Fethers-v5%407.1.0 implements the third point.
The first two are not really needed.
