### ISSUE TITLE
Feature: auto-generated types for solidity structs and events

### ISSUE THREAD

**Issue by gitpusha** [dethcrypto/TypeChain#398]
- "ethers": "5.3.0"

- "@typechain/ethers-v5": "7.0.0"

-   "typechain": "5.0.0"

Typechain is generating this for a solidity function that is accepting a struct as input and also returns an array of structs as output:

**Solidity:**

```solidity
struct CanExecData {
    uint256 id;
    address user;
    uint256 minimumHF;
    address colToken;
    address spender;
}

struct CanExecResult {
    uint256 id;
    string isPositionSafe;
    string isATokenAllowed;
    string message;
}

    function multiCanExecute(CanExecData[] memory _canExecDatas)
        external
        view
        returns (CanExecResult[] memory)
```

**Typechain:**

```typescript
  multiCanExecute(
    _canExecDatas: {
      id: BigNumberish;
      user: string;
      minimumHF: BigNumberish;
      colToken: string;
      spender: string;
    }[],
    overrides?: CallOverrides
  ): Promise<
    ([BigNumber, string, string, string] & {
      id: BigNumber;
      isPositionSafe: string;
      isATokenAllowed: string;
      message: string;
    })[]
  >;
```

**It would be really useful if typechain also generated and exported interface for every solidity struct with correct field names.** 

Otherwise we have to resort to defining those types ourselves:

```typescript
// DO NOT MODIFY FIELDS: must match solidity struct
export interface CanExecData {
  id: string;
  user: string;
  minimumHF: BigNumber;
  colToken: string;
  spender: string;
}

// DO NOT MODIFY FIELDS: must match function return type
export interface CanExecResult {
  id: string;
  isPositionSafe: string;
  isATokenAllowed: string;
  message: string;
}
```

And then do an unsafe cast via `unknown` to those types:

```typescript
export const multiCanExecute = async (
  canExecDatas: CanExecData[]
): Promise<CanExecResult[]> => {
  return refinanceResolver.multiCanExecute(
    canExecDatas
  ) as unknown as CanExecResult[];
};
```

I suppose that if typechain correctly auto-generates the `CanExecResult` struct type, then the cast via `unknown` would not be necessary because it `intersects` in the `ethers.js` function result type

```
Promise<
    ([BigNumber, string, string, string] & {
      id: BigNumber;
      isPositionSafe: string;
      isATokenAllowed: string;
      message: string;
    })[]
  >
  ```
  
Maybe typechain could also make use of the auto-generated struct type internally in its definitions like so (if it doesnt cause trouble with ethers.js compatibility)?  
 
 ```typescript
  multiCanExecute(
    _canExecDatas: CanExecData[],
    overrides?: CallOverrides
  ): Promise<
    ([BigNumber, string, string, string] & CanExecResult)[]
  >;
```
  
 **Either way it would be super useful if typechain also auto-generated and exported types for Solidity structs, to avoid human error.**

**The same can be said for solidity events.**

Thanks for this amazing tool @krzkaczor ! We use it every day and love it!

**Comment by krzkaczor** [comment]
Support for events released in https://github.com/dethcrypto/TypeChain/releases/tag/%40typechain%2Fethers-v5%407.1.0 

h/t @zemse

**Comment by krzkaczor** [comment]
Unfortunately, information (like names) about structs is not exposed to the ABI file so there is nothing that we can do.

**Comment by krzkaczor** [comment]
@zemse pointed out that sometimes structs appear in abi 👏 

I did some testing and it appears that:
* `"internalType": "struct StructName"` will be generated if the struct is used as input or output of an exposed method
* will NOT appear if structs are only used internally or only in storage variables like mappings (this case is quite unexpected)

**Comment by farreldarian** [comment]
What about enum? I see that it also has `"internalType": "struct EnumName"`

**Comment by zemse** [comment]
@farreldarian Are you sure about that? I'm seeing it as `"internalType": "enum DataTypesInput.Enum1"`

**Comment by PoolPirate** [comment]
Is it a necessity to only rely on the ABI? The AST does contain enum / struct information and could be used for this.
<img src="https://i.imgur.com/foxHgZy.png"/>

In order to only generate the necessary enums (no internal ones) it will have to be matched against the ABI though.

**Comment by zemse** [comment]
> Is it a necessity to only rely on the ABI? The AST does contain enum / struct information and could be used for this.

Can you pls point out how using AST + ABI can generate better types?
