### ISSUE TITLE
It it possible to use typechain in a javascript project with commonjs modules?

### ISSUE THREAD

**Issue by poma** [dethcrypto/TypeChain#455]
I have a JS hardhat project and trying to use typescript to get better autocompletion in vscode. It doesn't seem to work out of the box, but if I do something like

```js
const { Foo } = require('./typechain/index')
/** @type {Foo} */
let foo
```

autocompletion starts working, but the first line will obviously fail during execution when it tries to import ts file into a js project.

It also seems to work if I replace all `import` in generated code with `require`. I've tried to experiment with `jsconfig.json` files but no luck there.

How do I configure the project properly?

**Comment by krzkaczor** [comment]
Have you seen this? https://stackoverflow.com/questions/51061285/how-to-use-custom-typings-in-js-project

**Comment by poma** [comment]
It works when I put a simple test *.d.ts file into typechain dir. But as soon as the file contains `import` keyword (which all typechain files do) autocomplete starts to ignore it.

**Comment by hasparus** [comment]
Hey @poma, does using `/** @type {import("./typechain").Foo} */`. help?

**Comment by krzkaczor** [comment]
I am gonna close this as it's not strictly related to TypeChain. If this is still a problem please reopen as "github discussion".
