### ISSUE TITLE
Example not generating contract typings

### ISSUE THREAD

**Issue by M0kY** [dethcrypto/TypeChain#471]
I've tried running the `ethers-v5` example and only the` commons.ts` and` index.ts` files were generated.

![generated](https://user-images.githubusercontent.com/46133205/133933230-06908c20-59a3-489f-9267-a07cb86f2048.PNG)
![2b9f74100c39e92dfe643e33425c5819](https://user-images.githubusercontent.com/46133205/133933231-a51ab0ce-1ee3-4075-a634-a4758a9537f8.png)

The same happens with my project. Am I using it wrong?

**Comment by zemse** [comment]
That is weird, is it possible for you to push to a temp repo and make it public? I'll check that

**Comment by M0kY** [comment]
Ah I found what was the issue `ts-gen: 'abi/*' matched 0 files.`
It was caused by the `'` around `abi/*.json`
I guess it's only an issue for Windows users. 😅

**Comment by krzkaczor** [comment]
Ahh, right... Releated: https://github.com/dethcrypto/TypeChain/issues/411

**Comment by krzkaczor** [comment]
I ll ship a fix in a sec
