### ISSUE TITLE
Trying to install Typechain

### ISSUE THREAD

**Issue by andrewalisa** [dethcrypto/TypeChain#477]
I am trying to install TypeChain and I get the following errors:
![image](https://user-images.githubusercontent.com/11934220/134615503-3ea3d187-e314-444c-9237-484575fd6e43.png)

I noticed that the [OpenZeppelin-Solidity ](https://www.npmjs.com/package/openzeppelin-solidity) package has been deprecated. Maybe TypeChain needs to account for the @openzeppelin/contracts directory?

**Comment by krzkaczor** [comment]
Hey! We don't rely on any OpenZeppelin libs. Can you push repro somewhere?

**Comment by andrewalisa** [comment]
Hey! I resolved it. We can mark this as closed.

**Comment by krzkaczor** [comment]
Can you share what was the problem?

**Comment by andrewalisa** [comment]
Sure, I used the command 

`npx typechain --target=(ethers-v4|ethers-v5|truffle-v4|truffle-v5|web3-v1|path-to-custom-target) [glob]`

It didn't seem clear in the TypeChain docs that I had to use npx. 

I am using Windows 10 as well by the way. Maybe I should have been using Linux?
