### ISSUE TITLE
TypeScript issue with ethers-v5

### ISSUE THREAD

**Issue by zveljkovic** [dethcrypto/TypeChain#482]
Hi, when using ethers-v5 target I get "TS2352: Conversion of type 'Promise<Contract>' to type 'Promise<BasicContract>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first."

Basic Contract is my class. The error is in generated factory on many methods.

Error is corrected when I go to generated contract and remove BaseContract from
```
import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
``` 
and add it below this import as 
```
import { BaseContract } from "@ethersproject/contracts";
``` 

My dependency list is 
```
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.0",
    "@nomiclabs/hardhat-waffle": "^2.0.0",
    "@typechain/ethers-v5": "^7.1.2",
    "@typechain/hardhat": "^2.3.0",
    "@types/chai": "^4.2.22",
    "@types/mocha": "^9.0.0",
    "@types/node": "^16.10.1",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.0.0",
    "ethers": "^5.0.0",
    "hardhat": "^2.6.2",
    "hardhat-gas-reporter": "^1.0.4",
    "ts-node": "^10.2.1",
    "typechain": "^5.1.2",
    "typescript": "^4.4.3"
  }
  ```

**Comment by krzkaczor** [comment]
Bump ethers version please. You may need to force it with resolutions field.

**Comment by zveljkovic** [comment]
Thank you! I solved it by doing what you told me. I increased the ethers version in package.json to 

    "ethers": "^5.4.7", 
    
as it was the latest at this time. After `npm i` the typechain generated code worked flawlessly.

**Comment by sebastiantf** [comment]
seeing the same issue rn with latest npm pulls. also tried pinning versions:
```
"@typechain/ethers-v5": "9.0.0",
"typechain": "7.0.0",
"ethers": "5.5.4",
```
