### ISSUE TITLE
I'm getting network error when try to connect to the factories

### ISSUE THREAD

**Issue by nastari** [dethcrypto/TypeChain#485]
I'm trying to add typechain in my code but it's giving a network error, I already have a provider instance running in my dapp and it's only working when I create another instance from an rpc url.

My idea was to pass the method below as the second parameter to connect to the generated factories.

```
export function getProviderOrSigner(library: Web3Provider, account?: string): Web3Provider | JsonRpcSigner {
  return account ? getSigner(library, account) : library;
}

function getSigner(library: Web3Provider, account: string): JsonRpcSigner {
  return library.getSigner(account).connectUnchecked();
}
```

import { useWeb3React } from '@web3-react/core';

 const { library, account } = useWeb3React();

  const useTokenBalance = async () => {

    if (account && library) {
     
      const erc20 = ERC20__factory.connect( '0x43b... ', getProviderOrSigner(library, account));

      const balance = parseInt( ( await erc20.balanceOf(account) )._hex ,  16 );
      return balance;
    }
  };

...

**Unhandled Rejection (Error): underlying network changed (event="changed", network={"name":"unspecified","chainId":0,"ensAddress":null,"_defaultProvider":null}, detectedNetwork={"name":"bnb","chainId":56,"ensAddress":null,"_defaultProvider":null}, code=NETWORK_ERROR, version=providers/5.4.5)**

```
Web3Provider.<anonymous>
/home/Documents/new/src.ts/base-provider.ts:835
  832 | // First time scanning. We start a little earlier for some
  833 | // wiggle room here to handle the eventually consistent nature
  834 | // of blockchain (e.g. the getTransactionCount was for a
> 835 | // different block)
      | ^  836 | if (scannedBlock == null) {
  837 |     scannedBlock = lastBlockNumber - 3;
  838 |     if (scannedBlock < replaceable.startBlock) {
```

deps: {
   "@typechain/ethers-v5": "^7.1.0",
    "@web3-react/core": "^6.1.9",
}

the typings are correct and my calls without typechain are working, I'm not getting a compilation error, but a runtime error...

**Comment by nastari** [comment]
It was my mistake. There is absolutely no problem with typechain, but an implementation of mine. At the time of retrieving the chainId I was transforming the hexadecimal value to integer using base 10, instead of 16 in the ethers package. The problem was deeper and in other tests the error persisted. Grateful!

```
export default function getLibrary(provider: any): Web3Provider {

  const chainIdOrAny = typeof provider.chainId === 'number' ? provider.chainId : typeof provider.chainId === 'string' ? parseInt(provider.chainId, **16**) : 'any';

  const library = new Web3Provider(provider, chainIdOrAny);

  return library;
}

```

**Comment by zemse** [comment]
If this is not a problem anymore, closing the issue for now. Pls reopen if that's not the case.
