### ISSUE TITLE
[Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.4.1)]

### ISSUE THREAD

**Issue by Albert-Gao** [dethcrypto/TypeChain#521]
Trying to send LINK from address to another address
Was following the example code, but getting this error, I read from the ethers repo that you just connect your wallet as the signer of a contract, but from the interface of TypeChain, I do not know how to add a signer.

```typescript
export class ERC20Service {
  tokenSymbol: ITokenSymbol;
  provider: ethers.providers.InfuraProvider;
  contract: ERC20SmartContracts;
  decimals: number;
  wallet: ethers.Wallet;

  constructor(
    tokenSymbol: IERC20TokenSymbol,
    networkName: IEthNetwork,
    privateKey: string,
  ) {
    const tokenInfo = ERC20Tokens[tokenSymbol];
    const networkInfo = tokenInfo.networks[networkName];

    this.tokenSymbol = tokenSymbol;
    this.provider = new ethers.providers.InfuraProvider(networkName, {
      projectId: 'AAA',
      projectSecret: 'BBB',
    });

    this.wallet = new ethers.Wallet(privateKey, this.provider);

    this.contract = ERC20SmartContracts__factory.connect(
      networkInfo.tokenContractAddress,
      this.provider,
    );

    this.contract.connect(this.wallet);

    this.decimals = networkInfo.decimals;
  }

  getWalletBalance = async () => {
    const balance = await this.contract.balanceOf(
      this.wallet.address,
    );

    return balance;
  };

  transfer = async ({
    to,
    value,
  }: {
    to: string;
    value: BigNumberish;
  }) => {
    console.log('hahah');
    return this.contract.transferFrom(this.wallet.address, to, value);
  };
}
```

Calling `getWalletBalance` works great, but calling the `transfer` shows an error:

> [Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.4.1)]

Seems I am connecting this contract twice, one with the token address and one with the wallet (`this.contract.connect(this.wallet)`), I do not know if that causes the problem or not, but this is the only information I got from the example.

Also tried `this.contract.connect(this.provider.getSigner());` instead of the `wallet`, got an error too, `Error: API provider does not support signing`

What am I missing here? :)

**Comment by Albert-Gao** [comment]
Found what I am missing! 

```typescript
    this.contract = ERC20SmartContracts__factory.connect(
      networkInfo.tokenContractAddress,
      this.wallet,
    );
```

Beautiful! Thanks for the beautiful typegen!

**Comment by krzkaczor** [comment]
Glad that you figured it out!

Sidenote: https://github.com/dethcrypto/eth-sdk simplifies the process of managing ABIs and writing boilerplate code. You might find it interesting!

**Comment by Hp1923** [comment]
please help me......



Uncaught:
Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.5.0)
    at Contract.<anonymous> (C:\Users\Indium Software\hps\node_modules\@ethersproject\contracts\lib\index.js:416:16)
    at __awaiter (C:\Users\Indium Software\hps\node_modules\@ethersproject\contracts\lib\index.js:19:12)
    at new Promise (<anonymous>)
    at C:\Users\Indium Software\hps\node_modules\@ethersproject\contracts\lib\index.js:23:71
    at Object.next (C:\Users\Indium Software\hps\node_modules\@ethersproject\contracts\lib\index.js:29:53)
    at step (C:\Users\Indium Software\hps\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Contract.<anonymous> (C:\Users\Indium Software\hps\node_modules\@ethersproject\contracts\src.ts\index.ts:412:20)
    at Logger.throwError (C:\Users\Indium Software\hps\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at Logger.makeError (C:\Users\Indium Software\hps\node_modules\@ethersproject\logger\src.ts\index.ts:225:28) {
  reason: 'sending a transaction requires a signer',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'sendTransaction'
