### ISSUE TITLE
Add option to maintain directory structure in output folder

### ISSUE THREAD

**Issue by RyanRHall** [dethcrypto/TypeChain#545]
I think it would be beneficial to have the option to _turn off_ the directory flattening for typechain output. If I am using hardhat and typechain with contracts A, and B, then default config yields the following results:

```
src/                       <-- my contracts
  A/
    ContractA.sol
  B/
    ContractB.sol
artifacts/                 <-- hardhat
  src/
    A/
      ContractA.sol/...
    B/
      ContractB.sol/...
typechain/                 <-- typechain
  ContractA.d.ts
  ContractB.d.ts
```
Notice that typechain flattens the folder hierarchy. This usually fine, **unless you have contracts with the same name.** Ex...
```
src/
  A/
    Foo.sol
  B/
    Foo.sol
artifacts/
  src/
    A/
      Foo.sol/...
    B/
      Foo.sol/...
typechain/
  Foo.d.ts                 <-- only one file generated
```
And now one of the contracts is totally erased (I'm assuming the last one takes precedence). I would love to include an option like `maintainFolderHeirarchy` or something in the typechain config that will help avoid this scenario.

You might ask "why would you have two contracts with the same name"? Good question. I'm sure there are tons of reasonable use cases, but I'll outline mine. I have two implementations of the same library. One for internal use and one for external use. They have the exact same api, but fit different needs. My folder structure is...
```
src/
  libraries/
    internal/
      FooLib.sol
    external/
      FooLib.sol
```

**Comment by chrisfarms** [comment]
I hit this name clashing and since it's not an error it was pretty confusing for a while.

In my case I'm using the hardhat builder and it was a solidity `interface` used internally in one contract clobbering the file for an actual contract.

I think mimicking the artefact structure that hardhat produces (each .sol file becomes a directory) would make the most sense.

**Comment by nkuba** [comment]
I experienced the same problem. In my use case, I'm using contracts from an external package, which duplicates the names of some contracts defined in my project.

I'm looking forward to a fix! 🤞🏻
