### ISSUE TITLE
Add CLI flag to allow ignore TypeScript errors in generated code

### ISSUE THREAD

**Issue by hasparus** [dethcrypto/TypeChain#546]
We'd obviously prefer to write TypeChain in TypeScript as strong and safe as possible, but we can't guarantee that user project's config won't be stricter, revealing errors in generated code that weren't caught during the build.

I'd like to propose adding `--ts-nocheck` CLI flag and `process.env.TYPECHAIN_TS_NOCHECK` environment variable to add `/* @ts-no-check */ to generated files. This would allow users to workaround problems like https://github.com/dethcrypto/TypeChain/issues/393 on their side before they're fixed in TypeChain.

@krzkaczor what do you think?

**Comment by krzkaczor** [comment]
How would you compare your solution to the one presented in: https://github.com/dethcrypto/TypeChain/pull/543 ?

**Comment by hasparus** [comment]
#543 is proper solution for specific case. This issue is workaround for general case. Ideally, I'd have both.

**Comment by krzkaczor** [comment]
This might be a solution to fix some of the issues (like #393) but we need to warn users that this can hide some important problems and definitely this shouldn't be the default. Also, are you positive that `/* @ts-no-check */` works inside TS files?

**Comment by hasparus** [comment]
@krzkaczor
