### ISSUE TITLE
Bug: SyntaxError while generating typechain for projects

### ISSUE THREAD

**Issue by UncleGrandpa925** [dethcrypto/TypeChain#549]
Hi there.

So I have been experimenting with typechain for the past few days, and discovered that the current version of typechains cannot properly compile my company's project, with the following error

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/20136490/142034468-32229db6-4bbe-4e8a-bcfc-e9f73304324c.png">

However, if I revert all typechain-related packages to their latest versions before the added support for Solidity structs, everything will work normally. More specifically, the versions I reverted to were:
```
@typechain/hardhat@2.3.1
typechain@5.2.0
@typechain/ethers-v5@7.2.0
```

Here is how to recreate the error: 
- Clone [this repo](https://github.com/pendle-finance/pendle-core/tree/demo-issue-typechain)
- Run `yarn install`, then `yarn compile`

It would be super helpful if this error can be fixed! Thanks a lot!

**Comment by krzkaczor** [comment]
Releases:
- https://github.com/dethcrypto/TypeChain/releases/tag/%40typechain%2Fethers-v5%408.0.4
- https://github.com/dethcrypto/TypeChain/releases/tag/typechain%406.0.4
