### ISSUE TITLE
Confusing path for TypeChain

### ISSUE THREAD

**Issue by taiyangc** [dethcrypto/TypeChain#553]
Hello,

I believe TypeChain should make it clear that it only supports TypeScript bindings/interfaces for Solidity contracts.

For newcomers (such as myself), we've all read this excellent article about what TypeChain aimed to be https://blog.neufund.org/introducing-typechain-typescript-bindings-for-ethereum-smart-contracts-839fc2becf22

However to this date, it has somehow failed its original purpose. The generated wrapper at the time of the Medium article posting (4 years ago) was exactly what Dapp developers need today: completely generated wrappers for calling the contracts. Right now, only interfaces / typings are available, which developers still need to re-vamp in house to get a complete implementation working.

To give an analogy, this is like running `protoc` on a spec but stopping after retrieving the compiled `.pb.go` file but throwing away the rest of the client wrappers, then ask the team to write their own.

I do sincerely appreciate the work the community put into the project, but I would still like to be enlightened on a few project decisions:
1) Why going away from a complete generator solution, to just the typings?
2) If the reason is giving community more flexiblility in developing implementations, how hard would it be to develop a complete web3 or ethers generator so developers can write minimal code for interacting with contracts?
3) I do see at least one project (@0x/abi-gen) building what I had described, but I am wondering why the community hasn't built out a swagger or grpc-like solution/effort to push code generators to more languages in addition to TypeScript? Is there a project/community aiming to be the swagger for Solidity?

**Comment by krzkaczor** [comment]
@taiyangc you should check out https://github.com/dethcrypto/eth-sdk 

TypeChain tries to be unopinionated. Thanks to this it works in many different environments like hardhat/waffle. This was actually one of the learnings from the initial release. Coming up with own API takes a lot of effort and it's hard to make everyone happy. Currently, the quality of Web3 access libs (ethers.js, web3js) is totally different than what it used to be so it's easier to just be compatible with these libraries. 

Eth-SDK on the other hand is opinionated and focuses on rapid development. You should really give it a try.

**Comment by taiyangc** [comment]
Thank you for the information. I will definitely take a look. Sorry I couldn't find a better channel to communicate.

**Comment by krzkaczor** [comment]
I just added a note about eth-sdk to the readme. Closing this now.
