### ISSUE TITLE
Can I use TypeChain for client-side code?

### ISSUE THREAD

**Issue by grapevinegizmos** [dethcrypto/TypeChain#554]
I've used Typechain in my hardhat environment as I developed my contracts, test and middleware, but now I am working on a new project, which the consumer front end that end user can use to interact with the contracts that have already been deployed.  Being a bit of a newbie, I am somewhat confused about how to use the tooling.  In my development project it was very easy to use the typechain objects to call methods on my deployed contracts.  But I am not using hardhat on the front end website, and wondering if its possible to somehow use typechain to make it easier to interact with my deployed contracts, based on the ABI's (but not the .sol contracts) Ive iimported into my front end?

THanks.

**Comment by krzkaczor** [comment]
Yes! It's totally possible to manually set up ether.js contract instances and then cast them to TypeChain generated types to obtain type-safety. 

Luckily our new project makes it very easy to setup: https://github.com/dethcrypto/eth-sdk
