### ISSUE TITLE
Allow users to output types to multiple folders

### ISSUE THREAD

**Issue by adriandelgg** [dethcrypto/TypeChain#556]
Is there a way to output the generated types to multiple folders?

I want to be able to put the types in a `backend`, `frontend`, and the `hardhat` folder in my project.

**Comment by krzkaczor** [comment]
I recommend using a simple shell script to do post-processing like this.

**Comment by adriandelgg** [comment]
Is there a way to make the shell script run after running `npx hardhat typechain`?

**Comment by krzkaczor** [comment]
I don't think so. I would add a script in package.json that combines these 2.
