### ISSUE TITLE
Can TypeChain generate a list of contracts in addition to definitions

### ISSUE THREAD

**Issue by ShravanSunder** [dethcrypto/TypeChain#579]
I'm developing `scaffold-eth-typescript` and `eth-hooks`.  I was wondering if typechain could generate a index.ts file that would generate a record of contracts to factories as an index file?

for example if your contracts include `contract1.sol`, yourcontract.sol', 'contract2.sol', typechain would also generate an `index.ts` file
```
export const definitions = {
'contract1`: contract1__factory
`'yourcontract`: yourcontract__factory,
 ...
}
```

it would help to create a development environment that would autoload contracts with types.

**Comment by krzkaczor** [comment]
Hey. Yeah we definitely can look into how we can make typechain integrate better with other tools. Have you looked into [eth-sdk](https://github.com/dethcrypto/eth-sdk)?

**Comment by ShravanSunder** [comment]
@krzkaczor yes!  i'm using eth-sdk as well and they way it outputs indexes are extremely useful.

However, some of the contracts are locally generated.  Some are external contracts.  
- For the external contracts I'm using eth-sdk
- for local contracts that will be built and tested with hardhat, I am using typechain to generate everything.  However for typing and more automatic in the library, it would be great if an index.ts was generated with the rest of the files (definitions and factories)

**Comment by ShravanSunder** [comment]
@krzkaczor  if you can let me know which file to look at I can contribute =)
