### ISSUE TITLE
Solidity named tuple conversion decision 

### ISSUE THREAD

**Issue by poolpitako** [dethcrypto/TypeChain#580]
Hello, I started using this library recently.
My solidity code has the method signature:

```
  function pendingTradesById(uint256)
    external
    view
    returns (
      uint256 _id,
      address _strategy,
      address _tokenIn,
      address _tokenOut,
      uint256 _amountIn,
      uint256 _deadline
    );
```

and the generated typescript looks like this:
```
pendingTradesById(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, string, BigNumber, BigNumber] & {
        _id: BigNumber;
        _strategy: string;
        _tokenIn: string;
        _tokenOut: string;
        _amountIn: BigNumber;
        _deadline: BigNumber;
      }
    >;
```

I was wondering why the return type is a tuple intersected by an object, instead of just an object.
I am trying to mock the return of the method creating an object by hand and I couldn't.  I defined the following type:

```
export type PendingTrade = [BigNumber, string, string, string, BigNumber, BigNumber] & {
  _id: BigNumber;
  _strategy: string;
  _tokenIn: string;
  _tokenOut: string;
  _amountIn: BigNumber;
  _deadline: BigNumber;
};
```

and the way I could populate the object is doing a cast like this:
```
const pendingTrades: PendingTrade[] = [];
pendingTrades.push({
    _id: BigNumber.from("100"),
    _strategy: "0x0",
    _tokenIn: "0x0",
    _tokenOut: "0x0",
    _amountIn: BigNumber.from("1"),
    _deadline: BigNumber.from("200")
  } as PendingTrade);
```

is there a better way to create an instance of the type of the return type?

**Comment by dwardu** [comment]
Typechain merely declares TypeScript types for the untyped JavaScript objects already being returned by the underlying implementation, e.g. ethers.js.

From the [ethers.js library docs on `pure` or `view` methods](https://docs.ethers.io/v5/api/contract/contract/#Contract-functionsCall):
> The type of the result depends on the ABI. If the method returns a single value, it will be returned directly, otherwise a Result object will be returned with each parameter available positionally and if the parameter is named, it will also be available by its name.

This is why the return-type is a tuple intersected with an object. You can read the ethers.js code implementing this mechanism [here](https://github.com/ethers-io/ethers.js/blob/v5.5.3/packages/abi/src.ts/coders/tuple.ts#L23-L48).

You could implement something similar yourself for your mocks, e.g.:

```ts
type Point = [number, number] & { x: number, y: number }

let pUntyped: any = []

pUntyped = [3, 4]

Object.assign(pUntyped, { x: 3, y: 4 })
// // or simply
// pUntyped['x'] = 3
// pUntyped['y'] = 4

const pTyped = pUntyped as Point

{
    const [x, y] = pTyped;
    console.log(`x = ${x}, y = ${y}`) // prints "x = 3, y = 4"
}

{
    const {x, y} = pTyped;
    console.log(`x = ${x}, y = ${y}`) // prints "x = 3, y = 4"
}
```

**Comment by poolpitako** [comment]
@dwardu Great answer. thanks for your explanation!
