### ISSUE TITLE
Generate tagged unions for contract types

### ISSUE THREAD

**Issue by ShravanSunder** [dethcrypto/TypeChain#581]
If typechain can generate tagged unions for the contract types and factories this would make manipulation and sorting for libraries a lot easier.

For example in the definition of the following contracts
```
export class YourContract extends BaseContract {
  contractName: 'YourContract';
  connect(signerOrProvider: Signer | Provider | string): this;
...
```
```
export class Dai17 extends BaseContract {
  contractName: 'Dai17';
  connect(signerOrProvider: Signer | Provider | string): this;
...
```

I can use union discrimination and other typescript properties to properly type contracts that are stored in a library.  Such as a contract context in react.  

Related to #579  in that it allows for easy manipulation of types

**Comment by ShravanSunder** [comment]
perhaps related to #577

**Comment by krzkaczor** [comment]
closed with https://github.com/dethcrypto/TypeChain/pull/648
