### ISSUE TITLE
Hardhat: Error occured:  Not a valid ABI

### ISSUE THREAD

**Issue by damianlluch** [dethcrypto/TypeChain#594]
Hi, I'm having a problem generating types manually in Hardhat.
If I manually run 

`typechain --target=ethers-v5 artifacts/contracts/**/*.json glob`

I get the issue error

On the other hand, if I run

`npx hardhat compile`

The types are generated fine.

Any suggestions?

thanks

**Comment by krzkaczor** [comment]
The problem seems to be `.dbg` files generated by hardhat. You need to filter them out. Try this instead:

```
typechain --target=ethers-v5 "artifacts/contracts/**/*[!dbg].json"
```

Source: https://stackoverflow.com/questions/20638040/glob-exclude-pattern

Btw. Why do you want to run typechain via CLI in a harhdat project?

**Comment by peetzweg** [comment]
@red2678 I feel you. 
I stumbled upon this issue while adding `openzeppelin-contracts` to `@abimate`
Which actually tries to solve exactly this issue you are mentioning. ✌️ 

https://github.com/peetzweg/abimate

**Comment by vladfaust** [comment]
> The problem seems to be `.dbg` files generated by hardhat. You need to filter them out. Try this instead:
> 
> ```
> typechain --target=ethers-v5 "artifacts/contracts/**/*[!dbg].json"
> ```
> 
> Source: https://stackoverflow.com/questions/20638040/glob-exclude-pattern
> 
> Btw. Why do you want to run typechain via CLI in a harhdat project?

The pattern ignores contracts ending with `d`, `b` or `g` in their names. Changing it to `artifacts/contracts/**/*(!.dbg).json` doesn't work (`No files passed.`).
