### ISSUE TITLE
TypeChain with Vyper

### ISSUE THREAD

**Issue by FormidablePencil** [dethcrypto/TypeChain#596]
How would you get TypeChain to generate types for Vyper contracts. Solidity and Vyper generate the same abis in my understanding so I think it could work seamlessly. Thanks in advance.

**Comment by FormidablePencil** [comment]
There seems to be a bug in hardhat not generating types for vyper contracts. A temporary workaround can be found [here](https://github.com/dethcrypto/TypeChain/issues/146).

**Comment by krzkaczor** [comment]
fwiw: new version of the plugin was just released https://twitter.com/hardhathq/status/1484193829284728834?s=21
