### ISSUE TITLE
Change Factory postfix using ethers-v5

### ISSUE THREAD

**Issue by cmitjans-at-wiris** [dethcrypto/TypeChain#598]
I'm using typechain alongside with ethers-v5 and hardhat.

I have a contract named `Genesis` and the name of the generated factory results in `Genesis__factory`. This is weird, since I noticed in your ethers-v5 README that you use the POSTFIX `Factory`. 

Is it be possible to change this to use `Factory` as a postfix instead?

**Comment by krzkaczor** [comment]
Postfix is not configurable at the moment. We needed to pick something unique to not collide with contracts named like GenesisFactory :/

**Comment by cmitjans-at-wiris** [comment]
Are you planning on changing that? Can we create PR on this repo?

**Comment by krzkaczor** [comment]
@cmitjans-at-wiris I think it's a good addition. If you're willing to create a PR I am gonna merge it.
