### ISSUE TITLE
Generate .d.ts file

### ISSUE THREAD

**Issue by trnhgquan** [dethcrypto/TypeChain#609]
Hi there, 

As I understand, from now typechain only generate .ts file instead of .d.ts file, but when I try to import .ts file , I always get error below. And if I want to use .d.ts file? How could I generate that with current newest version ?
```
error - ./node_modules/.../Router__factory.ts 6:12
Module parse failed: Unexpected token (6:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
```

**Comment by krzkaczor** [comment]
I think you're trying to load ts file with a js loader. If you use webpack, by default it will treat files in node_modules as js.

**Comment by trnhgquan** [comment]
@krzkaczor thank you, let me check, but in case if I want to have .d.ts file? What should I do ? 
I m using: 
 "@typechain/ethers-v5": "9.0.0",
    "@typechain/hardhat": "^4.0.0",
    "typechain": "7.0.0"

**Comment by krzkaczor** [comment]
Yes. TC generally (apart from factories...) generates only typings. You need to create runtime object and later cast it to the desired type. 

Here are some examples: 
* https://github.com/dethcrypto/TypeChain/blob/master/examples/ethers-v4/src/index.ts#L13
* https://github.com/dethcrypto/TypeChain/blob/master/examples/ethers-v5/src/index.ts#L10


Also you might find [eth-sdk](https://github.com/dethcrypto/eth-sdk) useful if you're interacting with already deployed, mainnet contracts.

**Comment by trnhgquan** [comment]
thank you @krzkaczor
