### ISSUE TITLE
Incorrect Types Generated For Event Filter Args

### ISSUE THREAD

**Issue by red2678** [dethcrypto/TypeChain#621]
First, let me preface with  I am fairly new to Solidity and TypeChain (thank you for this package btw :] ). Perhaps I am doing something wrong. 

- solidity 0.8.0
- @typechain/ethers-v5 9.0.0

Given the following Solidity code:
`event Activate(address account, bool active);`

The following typescript is generated:
`Activate(account?: null, active?: null): ActivateEventFilter;`

The signature is correct, but the argument types are not. 

When I check the `ActivateEventFilter` just to see the return type, I get to 
`export type ActivateEventFilter = TypedEventFilter<ActivateEvent>;`

I then check `ActivateEvent` and I see it's typed correctly.
`export type ActivateEvent = TypedEvent<
  [string, boolean],
  { account: string; active: boolean }>;`

But if I try to use the filter, I get an error:
`const filter = contract.filters.Activate('123456789', true);`

Error: `Argument of type '"123456789"' is not assignable to parameter of type 'null | undefined'.` 

This is because `account?: null` is expected to be `null` or `undefined` (`?`)

---

I assume the error would be the same for the second argument. I followed the code to this line. 
https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/target-ethers-v5/src/codegen/events.ts#L67

Which ends up doing:
https://github.com/dethcrypto/TypeChain/blob/4e71ad5ef899e1dde6b56d5063bdd5b6eab6158f/packages/target-ethers-v5/src/codegen/events.ts#L74

Not sure why this is not working. The `eventArg.type` must be invalid. I can fork and try to get a `pr` if I can find an issue but thought I would post to see if you guys could more quickly fix or let me know what I am doing wrong.

Many thanks!

**Comment by red2678** [comment]
Discovered the issue. Event parameters must be indexed for proper typings output. Closing. Ty!

**Comment by Fernichter** [comment]
Hi, any news on this?
Still having the problem that the argument types are null.

Thanks
