### ISSUE TITLE
Error when using `typechain` + `hardhat` + `ethers-v5`

### ISSUE THREAD

**Issue by kihonq** [dethcrypto/TypeChain#630]
Same error occurred when using `@typechain/hardhat` plugin.

```
Error occured:  Cannot read properties of undefined (reading 'outDir')
Stack trace:  TypeError: Cannot read properties of undefined (reading 'outDir')
    at new Ethers .....
```

![image](https://user-images.githubusercontent.com/37780658/156226024-cb070e86-5709-42a9-91e8-3447d89de2c9.png)

**Comment by krzkaczor** [comment]
we will need a minimal repo with reproduction to fix this. Are you sure that you are running all packages in the newest version? looks like a version mismatch to me.
