### ISSUE TITLE
Unused type in new release

### ISSUE THREAD

**Issue by yorhodes** [dethcrypto/TypeChain#721]
```
'PromiseOrValue' is declared but never used.
```
with `"@typechain/ethers-v5": "10.1.0"` / `"typechain": "8.1.0"`

**Comment by jmrossy** [comment]
Is it coming from eslint or ts? if it's eslint we add the artifacts to eslintignore

**Comment by sbahman** [comment]
I think this might also be related to the issue I have been having! #686

**Comment by apottere** [comment]
This is also breaking our build, and there doesn't seem to be an easy automated fix.

I was able to reproduce this with `@typechain/ethers-v5@10.1.0` and `typechain@8.1.0`, but downgrading to `@typechain/ethers-v5@10.0.0` and keeping `typechain@8.1.0` seemed to work.
