### ISSUE TITLE
Typed checked parsing of events

### ISSUE THREAD

**Issue by mountainpath9** [dethcrypto/TypeChain#734]
Typechain generate types for contract events, but doesn't seem to provide a means of using these.

For example, in the ethers-v5 example, the generated typescript for the dai contract contains the following:

```
export interface TransferEventObject {
  src: string;
  dst: string;
  wad: BigNumber;
}
```

but in the example code that receives such events, the object above is not used, and the `wad` field is accessed via the untyped `Results` structure:

https://github.com/dethcrypto/TypeChain/blob/92faf28a91fa17a6cb9c34bd29ea9b2cae5d57b3/examples/ethers-v5/src/index.ts#L21

(leading to potential runtime errors). 

How are are the event types like `TransferEventObject` intended to be used?

**Comment by wong2** [comment]
What about `event.args as TransferEventObject`?

**Comment by samlaf** [comment]
> the wad field is accessed via the untyped Results structure
I don't think this is true. `queryFilters` does returned a typedEvent. I think this is the code generated for this type (https://github.com/dethcrypto/TypeChain/blob/47ab6513aaf960ce2a0425fdf6e0561ca482b182/packages/target-ethers-v5/src/codegen/events.ts#L92).

For example, in my case, it generates:
```
  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

export interface TypedEvent<
  TArgsArray extends Array<any> = any,
  TArgsObject = any
> extends Event {
  args: TArgsArray & TArgsObject;
}
```
I think your `transferEventObject` here would take the place of `TArgsObject` (though not 100% sure about this).

Anyhow.. maybe your IDE is not setup correctly if you don't see the types?

**Comment by mountainpath9** [comment]
@samlaf thanks - you are correct that `queryFilter` does return a typed event result - I just guessed that this was not the case when looking at the ethers-v5 example  in this repo.

But I'm not using `queryFilter`. Rather I'm looking for some equivalent statically typed means of processing [the events generated by a specific transaction and returned inside a contract receipt](https://github.com/ethers-io/ethers.js/blob/608864fc3f00390e1260048a157af00378a98e41/packages/contracts/src.ts/index.ts#L102).

**Comment by samlaf** [comment]
@mountainpath9 I opened an issue for that exact use case: https://github.com/dethcrypto/TypeChain/issues/736

But basically typechain can't really type the events because that would require dynamic types (how can it know in advance all the events that are going to be emitted by the transaction?). So what you have to do is to filter the events for the one you are looking for (filter based on event name+topics), and then manually typecase the event to the one generated by typechain. It's a bit annoying... but it works.

**Comment by mountainpath9** [comment]
I'll close this issue in lieu of #736.
