### ISSUE TITLE
[ethers] Event fragments with struct arrays are falsely represented as tuple[]

### ISSUE THREAD

**Issue by Sparragus** [dethcrypto/TypeChain#785]
Very similar to https://github.com/dethcrypto/TypeChain/issues/387, but for events.

Typechain generates these event fragments:

```
functions: {
  "EventName(bytes32,address,tuple[],uint256)": EventFragment;
};
```

However when outputting the actual event fragments you will see that the fragment keys do not align. This is because typechain represents a `(address,uint256)[]` tuple-array as just `tuple[]`.

**Comment by emretepedev** [comment]
Same issue here.
