### ISSUE TITLE
Generated types are incompatible with ECMAScript modules

### ISSUE THREAD

**Issue by benesjan** [dethcrypto/TypeChain#793]
Hello,
when having `"module": "NodeNext"` in tsconfig.json, I get the following error:
![image](https://user-images.githubusercontent.com/13470840/202525232-0656d527-3b0e-4484-9c95-4cd63a64456b.png)

There doesn't seem to be an option to make typescript generate imports with file extensions. When I manually modify the typescript files and the extensions (`.js` or `/index.js`) to all the imports the issue disappears. Is there a way to enable this? If not would be great to have the support.

The repository I am working on is open-source so I can send a link if somebody would like to reproduce it.

Thank you

**Comment by silasdavis** [comment]
I have implemented support for this here: https://github.com/dethcrypto/TypeChain/pull/799

**Comment by benesjan** [comment]
@silasdavis Thank you! 👍

**Comment by pablomendezroyo** [comment]
This should not be closed as long as the PR is still opened

**Comment by krzkaczor** [comment]
Merged as: https://github.com/dethcrypto/TypeChain/pull/840

**Comment by pablomendezroyo** [comment]
For those running into this issue, I just execute a js script that add the `.js` extension to relative imports right after the typechain command as follows
```bash
&& node addExtensionJs.js
```

The script command: https://github.com/dappnode/toolkit/blob/main/addExtensionJs.js

**Comment by TahaSha** [comment]
Im running into the same issue as @pablomendezroyo where the `.js` isn't being added as the suffix. For now, I don't mind adding it manually, 

I was also getting this error in my `index.ts` file:
```
Cannot find module './factories.js' or its corresponding type declarations.
```
For the line:
```
export * as factories from "./factories.js";
```

**Comment by jmrossy** [comment]
@krzkaczor  The output when --node16-modules is enabled is almost correct but is still not valid ESM code. The output includes both direct exports and rolled up exports using the `* as Foo` syntax, which imports from barrel files that **do not** include the needed file extension. See here for an example: https://github.com/dethcrypto/TypeChain/pull/840/files#diff-a13cd542099b350a17167268ac727e5d459fae33143fd0a1baf4cbb77f191f51R5

The line should be `export * as factories from "./factories.js"`, or preferably excluded altogether.

Is there a way to disable the `* as` exports which are unnecessary and undesirable as they reduce the effectiveness of tree shaking?

I see this is the same issue that was [raised here](https://github.com/dethcrypto/TypeChain/issues/819) and was supposedly fixed but I'm still seeing it use the latest typechain version

_Edit_: I've found the problem and submitted a PR to fix here: https://github.com/dethcrypto/TypeChain/pull/898
