### ISSUE TITLE
Support for ethers v6

### ISSUE THREAD

**Issue by vladikopl01** [dethcrypto/TypeChain#809]
Seem that `ethers` has changed the latest workable version up to `v6.0.5`, so how soon it be possible to use `typechain`? Or are there already some workarounds to use the new version of `ethers` with the existing `typechain`?

[Reference](https://www.npmjs.com/package/ethers)

**Comment by krzkaczor** [comment]
Yes. @zemse implemented it here: https://github.com/dethcrypto/TypeChain/pull/803 (there's a npm package of that target). 

There's gonna be official beta release today.

**Comment by agualis** [comment]
This ethers6 integration is not included in the main [README](https://github.com/dethcrypto/TypeChain/blob/master/README.md). Is it still considered beta?
