### ISSUE TITLE
ethers-v6: Please consider implementing `Result` methods like `toArray()` and `toObject()`

### ISSUE THREAD

**Issue by shirotech** [dethcrypto/TypeChain#817]
https://github.com/ethers-io/ethers.js/blob/main/src.ts/abi/coders/abstract-coder.ts#L138

https://github.com/ethers-io/ethers.js/blob/main/src.ts/abi/coders/abstract-coder.ts#L153

Both methods are invaluable to most common use-cases. Thank you.

**Comment by shirotech** [comment]
Have made a PR for this: #818

**Comment by emretepedev** [comment]
Is there any update here?

**Comment by shirotech** [comment]
I'm not really sure, it's been so long, @krzkaczor please let me know anything you need on this before it can be merged? Thank you.

**Comment by handanyolak** [comment]
Is there any update here? I got a lot of type errors because of this.

**Comment by emretepedev** [comment]
Same issue here.

**Comment by shirotech** [comment]
Seems this project is deprecated, maintainer is not responsive and so I have moved onto viem as mentioned in the README.md, I will not spend any more time on this. Feel free to fork and open up another PR (Good luck on getting it merged). Cheers.
