### ISSUE TITLE
Feature request: add support for viem

### ISSUE THREAD

**Issue by bitbyrey** [dethcrypto/TypeChain#844]
I was happily using wagmi and typechain together. But the latest version of wagmi merged to viem (https://viem.sh/) instead of ethers. Please consider supporting viem if possible. ❤️

**Comment by krzkaczor** [comment]
With viem, there is no longer a need for TypeChain. Smart contract interactions are typed using abi-type. Users simply need to store ABI in TypeScript files and declared `as const`.

  Please reopen if I am missing something.
